<ListaSalariosScreen@MDScreen>:
    name: "ListaSalariosScreen"

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.bg_dark
        padding: "10dp"
        spacing: "10dp"
    MDTopAppBar:
        title: "Tabla de Salarios"
        elevation: 4
        md_bg_color: app.theme_cls.primary_color
        left_action_items:
            [["home", lambda x: app.ir_a("HomeScreen")],
            ["arrow-left", lambda x: app.ir_a("ListaFuncionariosScreen")]]
        right_action_items:
            [["arrow-right", lambda x: app.ir_a("ProgramadoresScreen")]]

        MDLabel:
            text: "Sueldos Registrados"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDCard:
            radius: 20
            padding: "15dp"
            md_bg_color: app.theme_cls.bg_light
            orientation: "vertical"

            ScrollView:
                MDBoxLayout:
                    id: contenedor_tabla
                    orientation: "vertical"
                    adaptive_height: True
