<ProgramadoresScreen@MDScreen>:
    name: "ProgramadoresScreen"

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.bg_dark
        padding: "10dp"
        spacing: "10dp"

        MDTopAppBar:
            title: "Equipo de Programadores"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left-bold-box-outline", lambda x: app.ir_a("HomeScreen")]]
        MDLabel:
            text: "Conoce al equipo"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        ScrollView:
            MDGridLayout:
                cols: 2
                adaptive_height: True
                spacing: "15dp"
                padding: "10dp"

                MDCard:
                    radius: 20
                    md_bg_color: app.theme_cls.bg_light
                    orientation: "vertical"
                    size_hint_y: None
                    height: "300dp"
                    padding: "10dp"

                    FitImage:
                        source: "images/telmo.jpg"
                        size_hint_y: 0.8
                        radius: [20,20,0,0]

                    MDLabel:
                        text: "Juan Ignacio Telmo"
                        halign: "center"
                        theme_text_color: "Custom"
                        text_color: 0, 0, 0, 1
                        size_hint_y: 0.2

                MDCard:
                    radius: 20
                    md_bg_color: app.theme_cls.bg_light
                    orientation: "vertical"
                    size_hint_y: None
                    height: "300dp"
                    padding: "10dp"

                    FitImage:
                        source: "images/carlitos.jpg"
                        size_hint_y: 0.8
                        radius: [20,20,0,0]

                    MDLabel:
                        text: "Hilario Reddel"
                        halign: "center"
                        theme_text_color: "Custom"
                        text_color: 0, 0, 0, 1
                        size_hint_y: 0.2

                MDCard:
                    radius: 20
                    md_bg_color: app.theme_cls.bg_light
                    orientation: "vertical"
                    size_hint_y: None
                    height: "300dp"
                    padding: "10dp"

                    FitImage:
                        source: "images/kim.jpg"
                        size_hint_y: 0.8
                        radius: [20,20,0,0]

                    MDLabel:
                        text: "Santiago Kim"
                        halign: "center"
                        theme_text_color: "Custom"
                        text_color: 0, 0, 0, 1
                        size_hint_y: 0.2

                MDCard:
                    radius: 20
                    md_bg_color: app.theme_cls.bg_light
                    orientation: "vertical"
                    size_hint_y: None
                    height: "300dp"
                    padding: "10dp"

                    FitImage:
                        source: "images/marc.jpg"
                        size_hint_y: 0.8
                        radius: [20,20,0,0]

                    MDLabel:
                        text: "Bautista Marc"
                        halign: "center"
                        theme_text_color: "Custom"
                        text_color: 0, 0, 0, 1
                        size_hint_y: 0.2
