#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path
<ProgramadoresScreen>:
    name: "ProgramadoresScreen"
    BoxLayout:
        orientation: "vertical"
        padding: 10
        spacing: 20
        canvas.before:
            Color:
                rgba: 0.5, 0.5, 0.5, 1
            Rectangle:
                pos: self.pos
                size: 100, 80
        IconLeftWidget:
            icon: "home"
            on_press: app.ir_a("HomeScreen") 
            pos_hint: {'center_x':0, 'center_y':1}
        IconLeftWidget:
            icon: "arrow-left"
            on_press: app.ir_a("ListaSalariosScreen") 
            pos_hint: {'center_x':0, 'center_y':1}
        GridLayout:
            cols: 2
            rows: 4
            Image:
                source: ("images/telmo.jpg")
            Label:
                text:"Juan Ignacio Telmo"
                size_hint: 1, 1
                color: (0,0,1,1)

            Image:
                source: ("images/carlitos.jpg")
            Label:
                text:"Hilario Reddel"
                size_hint: 1, 1
                color: (0,0,1,1)

            Image:
                source: ("images/kim.jpg")
            Label:
                text:"Santiago Kim"
                size_hint: 1, 1
                color: (0,0,1,1)

            Image:
                source: ("images/marc.jpg")
            Label:
                text:"Bautista Marc"
                size_hint: 1, 1
                color: (0,0,1,1)