<ListaFuncionariosScreen@MDScreen>:
    name: "ListaFuncionariosScreen"

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.bg_dark
        padding: "10dp"
        spacing: "10dp"

        MDTopAppBar:
            title: "Funcionarios Argentinos"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["home", lambda x: app.ir_a("HomeScreen")]]
            right_action_items: [["arrow-right-thick", lambda x: app.ir_a("ListaSalariosScreen")],["magnify", lambda x: app.ir_a("BuscarFuncionariosScreen")]]

        MDLabel:
            text: "Listado de Funcionarios"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDCard:
            radius: 20
            padding: "15dp"
            md_bg_color: app.theme_cls.bg_light
            orientation: "vertical"
            size_hint_y: 1

            MDBoxLayout:
                id: contenedor_tabla
                orientation: "vertical"
                size_hint_y: 1
