#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path
<ListaFuncionariosScreen>:
    name: "ListaFuncionariosScreen"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.9, 0.9, 0.9, 1
            Rectangle:
                pos: self.pos
                size: self.size

        IconLeftWidget:
            icon: "home"
            on_press: app.ir_a("HomeScreen")
        IconRightWidget:
            icon: "arrow-right"
            on_press: app.ir_a("ListaSalariosScreen")


        Label:
            text: "Lista de Funcionarios Argentinos"
            color: 0, 0, 0, 1
            font_size: 32
        BoxLayout:
            id: contenedor_tabla
            orientation: "vertical"
            size_hint: 1, 1
            
