<LoginScreen@MDScreen>:
    name: "LoginScreen"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "20dp"
        md_bg_color: app.theme_cls.bg_dark

        MDTopAppBar:
            title: "Iniciar sesión"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left-bold-box-outline", lambda x: app.ir_a("HomeScreen")]]

        MDLabel:
            text: "Sistema de Sueldos"
            halign: "center"
            font_style: "H4"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDTextField:
            id: txt_usuario
            hint_text: "Correo electrónico"
            mode: "rectangle"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDTextField:
            id: txt_pass
            hint_text: "Contraseña"
            password: True
            mode: "rectangle"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDLabel:
            id: mensaje
            text: ""
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1

        MDRaisedButton:
            text: "Iniciar sesión"
            md_bg_color: app.theme_cls.primary_color
            size_hint: None, None
            size: "200dp", "50dp"
            pos_hint: {"center_x": 0.5}
            on_release: root.validar_datos()
