#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path
<LoginScreen>:
    name: "LoginScreen"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.9, 0.9, 0.9, 1
            Rectangle:
                pos: self.pos
                size: self.size
        IconLeftWidget:
            icon: "arrow-left"
            on_press: app.ir_a("HomeScreen")
        Label:
            text: "Sistema de Sueldos"
            font_size: 24
            color: (0.6, 0.6, 1, 1)
        TextInput:
            hint_text: "Correo electrónico"
            size_hint: None, None
            size: 300, 40
            pos_hint: {'center_x': 0.5}
        TextInput:
            hint_text: "Contraseña"
            password: True
            size_hint: None, None
            size: 300, 40
            pos_hint: {'center_x': 0.5}
        Button:
            text: "Iniciar sesión"
            size_hint: None, None
            size: 200, 50
            pos_hint: {'center_x': 0.5}
            background_color: (0.2, 0.6, 1, 1)
            on_press: app.ir_a("ListaScreen")