#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path
<LoginScreen>:
    name: "LoginScreen"
    BoxLayout:
        id: boxmensaje 
        orientation: "vertical"
        padding: 20
        spacing: 10
        canvas.before:
            Color:
                rgba: 0.788, 0.824, 0.824, 1
            Rectangle:
                pos: self.pos
                size: self.size
        IconLeftWidget:
            icon: "arrow-left"
            on_press: app.ir_a("HomeScreen")
        Label:
            text: "Sistema de Sueldos"
            font_size: 100
            bold: True
            color: (0, 0, 1, 1)
        TextInput:
            hint_text: "Correo electrónico"
            size_hint: None, None
            size: 450, 60
            pos_hint: {'center_x': 0.5}
        TextInput:
            hint_text: "Contraseña"
            password: True
            size_hint: None, None
            size: 450, 60
            pos_hint: {'center_x': 0.5}
        Button:
            text: "Iniciar sesión"
            font_size: 30
            size_hint: None, None
            size: 450, 75
            pos_hint: {'center_x': 0.5}
            on_press: app.ir_a("ListaFuncionariosScreen")
            background_color: (0, 0, 1, 0.8)