<BuscarFuncionariosScreen@MDScreen>:
    name: "BuscarFuncionariosScreen"

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.bg_dark
        padding: "10dp"
        spacing: "10dp"

        MDTopAppBar:
            title: "Búsqueda Avanzada"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items:["arrow-left-bold-box-outline", lambda x: app.ir_a("homeScreen")]
            right:_action_items: ["arrow-right-bold-box-outline", lambda x: app.ir_a("EdicionScreen")]
        MDLabel:
            text: "Búsqueda de Funcionarios"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDCard:
            radius: 20
            padding: "15dp"
            md_bg_color: app.theme_cls.bg_light
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height
            spacing: "10dp"

            MDTextField:
                id: buscar_nombre
                hint_text: "Apellido y nombre"
                mode: "rectangle"
                size_hint_x: 0.9
                pos_hint: {"center_x": 0.5}

            Spinner:
                id: spinner_columnas
                text: "Selecciona columna"
                values: []
                size_hint_x: 0.9
                pos_hint: {"center_x": 0.5}

            MDRaisedButton:
                text: "Buscar"
                md_bg_color: app.theme_cls.primary_color
                size_hint: None, None
                size: "180dp", "50dp"
                pos_hint: {"center_x": 0.5}
                on_release: func.buscar_funcionarios()
