<HomeScreen@MDScreen>:
    name: "HomeScreen"

    MDBoxLayout:
        orientation: "vertical"
        spacing: "40dp"
        padding: "30dp"
        md_bg_color: app.theme_cls.bg_dark

        MDLabel:
            text: "¡Hola, usuario!"
            halign: "center"
            font_style: "H3"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDBoxLayout:
            orientation: "vertical"
            spacing: "20dp"
            size_hint_y: None
            height: self.minimum_height
            pos_hint: {"center_x": 0.5}

            MDFillRoundFlatButton:
                text: "Iniciar sesión"
                pos_hint: {"center_x": 0.5}
                size_hint: None, None
                size: "260dp", "60dp"
                on_release: app.ir_a("LoginScreen")

            MDFillRoundFlatButton:
                text: "Registrarse"
                pos_hint: {"center_x": 0.5}
                size_hint: None, None
                size: "260dp", "60dp"
                on_release: app.ir_a("RegistroScreen")

            MDFillRoundFlatButton:
                text: "Registrarse"
                pos_hint: {"center_x": 0.5}
                size_hint: None, None
                size: "260dp", "60dp"
                on_release: app.ir_a("ProgramadoresScreen")
