<PerfilScreen@MDScreen>:
    name: "PerfilScreen"

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: app.theme_cls.bg_dark
        padding: "20dp"
        spacing: "20dp"

        MDTopAppBar:
            title: "Mi Perfil"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["home", lambda x: app.ir_a("HomeScreen")]]
            right_action_items: [["arrow-right-bold-box-outline", lambda x: app.ir_a("ListaFuncionariosScreen")]]

        MDLabel:
            text: "Información del usuario"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDCard:
            orientation: "vertical"
            padding: "20dp"
            spacing: "10dp"
            radius: 20
            md_bg_color: app.theme_cls.bg_light

            MDLabel:
                id: nombre_usuario
                text: "Nombre: "
                halign: "left"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

            MDLabel:
                id: email_usuario
                text: "Email: "
                halign: "left"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

            MDLabel:
                id: dni_usuario
                text: "DNI: "
                halign: "left"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        # Descomentar si querés un botón de edición
        # MDRaisedButton:
        #     text: "Editar perfil"
        #     md_bg_color: app.theme_cls.primary_color
        #     pos_hint: {"center_x": 0.5}
        #     size_hint: None, None
        #     size: "200dp", "50dp"
        #     on_release: app.ir_a("EditarPerfilScreen")
