<RegistroScreen@MDScreen>:
    name: "RegistroScreen"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "20dp"
        md_bg_color: app.theme_cls.bg_dark

        MDTopAppBar:
            title: "Registro"
            elevation: 4
            md_bg_color: app.theme_cls.primary_color
            left_action_items: [["arrow-left-bold-box-outline", lambda x: app.ir_a("HomeScreen")]]

        MDLabel:
            text: "Sistema de Sueldos"
            halign: "center"
            font_style: "H5"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 1

        MDLabel:
            id: datos_cargados
            text: ""
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            opacity: 1

        MDTextField:
            id: nombre_input
            hint_text: "Nombre de usuario"
            mode: "rectangle"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDLabel:
            id: nombre_invalido
            text: "Nombre inválido."
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            opacity: 0

        MDTextField:
            id: correo_input
            hint_text: "Correo electrónico"
            mode: "rectangle"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDLabel:
            id: correo_invalido
            text: "Correo inválido. Debe contener '@gmail.com' o '@pioix.edu.ar'"
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            opacity: 0

        MDTextField:
            id: dni_input
            hint_text: "DNI"
            mode: "rectangle"
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}
            input_filter: "int"

        MDLabel:
            id: dni_invalido
            text: "Debe tener 8 dígitos numéricos."
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            opacity: 0

        MDTextField:
            id: contrasena_input
            hint_text: "Contraseña"
            mode: "rectangle"
            password: True
            size_hint_x: 0.8
            pos_hint: {"center_x": 0.5}

        MDLabel:
            id: contrasena_invalida
            text: "Debe contener 8+ caracteres, una mayúscula, una minúscula y un número."
            halign: "center"
            theme_text_color: "Custom"
            text_color: 1, 0.2, 0.2, 1
            opacity: 0

        MDRaisedButton:
            text: "Registrarse"
            md_bg_color: app.theme_cls.primary_color
            pos_hint: {"center_x": 0.5}
            size_hint: None, None
            size: "200dp", "50dp"
            on_release: root.validar_registro(nombre_input.text, correo_input.text, dni_input.text, contrasena_input.text)
